// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zaozlozpwczrhpdwmvki.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inphb3psb3pwd2N6cmhwZHdtdmtpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg5NjYxNTksImV4cCI6MjA2NDU0MjE1OX0.q1DjrGE_87t81DNQ2QCS8gUgXV8WcPT7g4iprex8iQ4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);